before_script:
  - pwd
  - whoami
  - source ~/.bashrc
  - python --version

stages:
  - Setup
  - Code Quality

Setup:
  stage: Setup
  script:
    - pip install -r requirements.txt
  tags:
    - nonrooted

Code Quality:
  stage: Code Quality
  script:
    - pylint **/*.py