language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "tarball"
      env: PY=3

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Add conda-forge as lowest priority and enforce strict priority
  - conda config --append channels conda-forge
  - conda config --set channel_priority strict
  - conda create -q -n TEST python=$PY --file requirements.txt --file requirements-dev.txt
  - conda activate TEST

install:
  - pip install -e . --no-deps --force-reinstall

script:
  - |
    if [[ $TRAVIS_JOB_NAME == 'tarball' ]]; then
      python -m pep517.build --source --binary . --out-dir dist/
      check-manifest --verbose
      twine check dist/*
    fi
