name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - jupyter_server
  - ipywidgets
  - graphviz
  - nodejs
  - scikit-image
  - scikit-learn
  - geopandas
  - pip
  - pip:
    - graphviz
    - jupyter-server-proxy
    - cmocean
    - descartes
    - git+http://github.com/euroargodev/argodmqc_owc.git@master
    - netCDF4
